### ISSUE TITLE
Upload support `seed` tables (crosswalks + indicators)

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-extraction-loading#16]
@her43  can you upload some supporting tables to `\\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\dbt\v0\seeds`.  On the top of my mind (@alinasmahl1 feel free to edit this list):

- [x] zip to zcta crosswalks
- [x] zcta level indicators we want to use
- [ ] zcta to city crosswalk

**Comment by ran-codes** [comment]
@her43 can you share the zip to zcta crosswalks? (trying to put something together for the UHC weekly meeting next week 4/13)

Thanks!!

**Comment by alinasmahl1** [comment]
@ran-codes for zcta level indicators- let's go with soem classics. 

- svi (state specific)
- age compositoin (by 5 yr age grp), 
- racial composition
- racial-ethnic composition 
- poverty rate

**Comment by her43** [comment]
Sorry I must have missed this issue initially. I'll get this going now.

**Comment by her43** [comment]
> zip to zcta crosswalks

I didn't know what years exactly were wanted for this, so I created single-year tables for each year 2009 through 2021, then one for all years 2009-2021, and another (just for kicks) for 2010-2019. If there is a different year range we'd like for a table, it takes me like 60 seconds to get that done, so just let me know.

> @ran-codes for zcta level indicators- let's go with soem classics.
> 
> * svi (state specific)
> * age compositoin (by 5 yr age grp),
> * racial composition
> * racial-ethnic composition
> * poverty rate

@alinasmahl1  @ran-codes 

- Is there a certain ACS 5-year survey we'd like to use for this? I imagine just one 5-year survey is ok for now?
- All states? or just states we have/want HCUP data for?
- I don't have code for SVI, nor have I calculated it before. Ran, can you provide some code for this? (Since it's state level I'll plan on merging the state data with the ZCTA data by state name, which I have as a column in the zip-zcta crosswalk tables)
- I'm thinking one row per ZCTA, one column per indicator. Sound good?

**Comment by ran-codes** [comment]
#### Re: Crosswalks
@her43 thanks!!

#### Re: Indicators 

@her43 

> All states? or just states we have/want HCUP data for?

we only need for these state/years ([hcup-state-years.csv](https://github.com/Drexel-UHC/hcup-extraction-loading/files/11171342/hcup-state-years.csv))


> I don't have code for SVI, nor have I calculated it before. 

I'll take care of SVI


> I'm thinking one row per ZCTA, one column per indicator. Sound good?

perfect. I think add a column or year too? @alinasmahl1 we want longitudinal zcta level indicators right?

**Comment by ran-codes** [comment]
@her43 did you upload the crosswalk somewhere? I may have missed it.

**Comment by her43** [comment]
Should be in \\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\dbt\v0\seeds .

**Comment by ran-codes** [comment]
thanks!

**Comment by her43** [comment]
@ran-codes a note: whatever zip-zcta file you look at, there is only one match per zip code. It's not longitudinal, it's "best match" for the full span of years in the file.

**Comment by her43** [comment]
I completed and saved a file called "zcta_acs_7state_2018.rdata". I saved it in the same folder as the zip-zcta files from this morning.

There is 5-year ACS data for 2014-2018 in this file. I picked 2014-2018 because that year range overlaps with at least one of the years needed for each of the 7 states (AZ, FL, GA, KY, MA, NJ), according to the spreadsheet shared by @ran-codes earlier. I can quickly and easily create data for other years if desired, but I wasn't sure exactly what you want/need in terms of 5-year estimates (if only we could get 1-year estimates 😞) . Please advise.

I've included all the demographic distribution variables (as proportions) that were mentioned by @alinasmahl1, excluding state SVI. 

There are columns indicating the state (fips, abbreviation) and year (2018 in all cases for this data).

I also didn't know if we wanted Asian and PI separate or together, so I included both options, for both race alone, and race/ethnicity. (e.g. "race_asian", "race_pi", and "race_api" are all in the data)

The column names are pretty self-explanatory, but let me know if you're confused about the meaning of any of them.

**Comment by alinasmahl1** [comment]
Thank you @her43 re the 5 year- i think for now (as in for the presentation Wednesday) the 2014-2018 should be good. But Ran, if it's better for you do all of this at one time, then let's add in the other ACS files that align with each year, using the last year of the acs as the year.

**Comment by ran-codes** [comment]
thanks @her43 !! this is perfect for now (v0.2 hcup-dbt)

@alinasmahl1 @her43  we'll revisit indicators again for next release version (v0.3) and talk about adding longitudinal then. but this is good for our presentation next week. 

Note SVI will wait until v0.3 as well. As long as we have some indicators link as a POC for v0.2/the-presentation its fine i think,

CLosing for now. Thanks everyone!! 🍰

**Comment by ran-codes** [comment]
actually @her43  one last thing: can you provide a simple codebook for your ACS data. I attached a template for you to get started. just value_type and variable def is good.

- [ ] @her43 to fill out metadata for ACS indicators using [zcta_acs_7state_2018_codebook_template.csv](https://github.com/Drexel-UHC/hcup-extraction-loading/files/11179797/zcta_acs_7state_2018_codebook_template.csv)

**Comment by her43** [comment]
@ran-codes Sorry I recently noticed a typo in the name of one of the age groups, so I just re-ran the code to produce the zcta acs data. New version overwrites the version from yesterday.

I also took the opportunity to produce longitudinal versions for each state. Saved in the same folder.

codebook:
[zcta_acs_datasets_codebook.xlsx](https://github.com/Drexel-UHC/hcup-extraction-loading/files/11180973/zcta_acs_datasets_codebook.xlsx)

**Comment by ran-codes** [comment]
@alinasmahl1 @her43 I think we need another crosswalk.

A lot of the marts mention. `urbanicity` and `city`. So we need to clarify how we want ot operationalize these from ZCTA.  how you define city CBSA vs census place? 

Importantly, **need a crosswalk from ZCTA to `city`**.

**Comment by ran-codes** [comment]
@alinasmahl1 we can start with the 2010 census ZCTA to PLACE crosswalks to define city/urbanicity. thoughts?

**Comment by her43** [comment]
### Re: crosswalks

I'm also fan of the crosswalks downloadable from Missouri.edu's Geocorr tool (e.g., [geocorr2014](https://mcdc.missouri.edu/applications/geocorr2014.html), which lets you select any 2 geography types and create & download a crosswalk with % overlap (user can select population or land area as overlap criteria).

A sample of the list of geographies available for the 2010s. (2000s and 2020s are also available)
![image](https://user-images.githubusercontent.com/77505955/230677508-5645815d-c384-4dc2-a763-fc40523ea405.png)

**Comment by alinasmahl1** [comment]
@ran-codes @her43 I think the urbanicity is based on teh county ZIP and the RUCA codes no? https://www.ers.usda.gov/data-products/rural-urban-commuting-area-codes/

**Comment by alinasmahl1** [comment]
But for the ZCTA to city, I'm for using the 2010 ZCTA to place codes, if Heather thinks we could potentilly then align that with our other city/county code?

**Comment by ran-codes** [comment]
Thanks all for the suggestions. 

For now, here's the list of crosswalks loaded or v0.2. 

- **zip -> zcta**: crosswalk from heather
- **zip-> urban**: [2010 Rural-Urban Commuting Area Codes, ZIP code file](https://www.ers.usda.gov/data-products/rural-urban-commuting-area-codes/)
- **zcta -> place**: [2010 census relationship file ](https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.2010.html#par_textimage_674173622)


closing this issue for now. Lets revisit to make any changes in future release versions.  (v0.3 +). Please start a discussion if there are any concerns that we can address in the future.
